In [2]:
import numpy as np

nums = np.array([1,2,3,4,5])
print(nums[0:4:2])
print()

[1 3]



Slicing in 2D araay

In [ ]:
nums = np.array(
    [[11,12,13,14,15,16,17,18, 19, 20],
     [21,22,23,24,25,26,27,28, 29, 30]]
)

# print(nums[0][1:5])
# print(nums[1][1:5])
# print(nums[1, 1:5])
# print(nums[0:1]) --> Print first 
# print(nums[0 : 2, 3:6])
print(nums[:, 3:6])
# print(nums[-1 :: -1])
# print(nums[:: -1])
print(nums[-2])



In [ ]:
#Reshape
nums = np.array([1,2,3,4,5,6,7,8])
print(nums.reshape(8,1))
print(nums.reshape(2,4))

In [4]:
nums1 = np.array([1,2,3,4,5,6,7,8])
nums2 = np.array([11,12,13,14,15,16,17,18])
print(np.hstack([nums1, nums2]))

print(np.vstack([nums1, nums2]))

[ 1  2  3  4  5  6  7  8 11 12 13 14 15 16 17 18]
[[ 1  2  3  4  5  6  7  8]
 [11 12 13 14 15 16 17 18]]


Splitting data

In [9]:
nums = np.array(
    [[11,12,13,14,15,16,17,18, 19, 20],
     [21,22,23,24,25,26,27,28, 29, 30],
     [31,32,33,34,35,36,37,38, 39, 40],
     [41,42,43,44,45,46,47,48, 49, 50],
     [51,52,53,54,55,56,57,58, 59, 60],
     [61,62,63,64,65,66,67,69, 69, 70]
    ]
)

np.vsplit(nums,2)
hsplitted_array = np.hsplit(nums,2)
print(hsplitted_array[0])

[[11 12 13 14 15]
 [21 22 23 24 25]
 [31 32 33 34 35]
 [41 42 43 44 45]
 [51 52 53 54 55]
 [61 62 63 64 65]]
