In [ ]:
import numpy as np
print(np.__version__)

In [ ]:
list_nums = [10, 20, 30, 40, 50, 10.58]
np_array = np.array(list_nums, dtype='int64')
print(np_array)
print(type(np_array), np_array.dtype)
print(np_array.shape)
print(np_array.itemsize)
print(np_array.ndim)
print(np_array.size, len(np_array))

In [ ]:
list_nums = np.arange(0,15,3)
print(list_nums, list_nums.dtype)
print(list_nums[-1], list_nums[-2], list_nums[-3], list_nums[-4], list_nums[-5])

In [ ]:
list_nums = [
    [
        [1,0,0,0,0],
        [0,1,0,0,0]
    ],
     [
        [0,0,1,0,0],
        [0,0,26,1,0]
    ],
      [
        [0,0,0,0,1],
        [1,1,1,1,1]
    ]
]

np_array = np.array(list_nums, dtype='int64')
print(np_array)
print(type(np_array), np_array.dtype)
print(np_array.shape)
print(np_array.itemsize)
print(np_array.ndim)
print(np_array.size, len(np_array))

print(np_array[1][1][2])

In [8]:
# Zero matrix
zero_matrix = np.zeros((6,6), dtype='int64')
print(zero_matrix)

identity = np.identity(5, dtype='int32')
print(identity)

[[0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]]
[[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]]
